# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Chiara de Rege"
description: > # this means to ignore newlines until "email:"
   New York · Los Angeles

email: chiarade@gmail.com
#blog logo
logo: "/assets/images/cdr.svg"
# blog cover
cover: ""

name: 'Chiara de Rege'
author: 'Chiara de Rege'
# author_image: "/assets/images/author.jpg"

paginate:	1

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
# social:
#   - icon: phone
#     url:	tel:9176022266
#     title: t 917 602 2266
    # share_url: http://twitter.com/share
    # share_title: ?text=
    # share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  # - icon:	github
  #   url:	https://github.com/dirkfabisch
  #   desc:	Fork me on github
  #   share_url:
  #   share_title:
  #   share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
